version: "2"
services:
    # The data container is included here in case we don't run the db-compose because we are using an external database
    data:
        container_name: ace-data
        image: "quik/aceoperator-data:${project.version}"
        depends_on:
          - db
        links:
          - "db:db"
        networks:
          - "network"
        environment:
          - "ACE_SQL_HOST=${ACE_SQL_HOST}"
          - "ACE_SQL_ROOT_PASSWORD=${ACE_SQL_ROOT_PASSWORD}"
          - "ACE_SQL_USER=${ACE_SQL_USER}"
          - "ACE_SQL_PASSWORD=${ACE_SQL_PASSWORD}"
          - "ACE_SMTP_SERVER=${ACE_SMTP_SERVER}"
          - "ACE_SMTP_USER=${ACE_SMTP_USER}"
          - "ACE_SMTP_PASSWORD=${ACE_SMTP_PASSWORD}"
          - "LOAD_DEMO=${LOAD_DEMO}"
          - "RUN_SEED=${RUN_SEED}"
        volumes:
          - "${ACEOPERATOR_HOME}:/var/aceoperator"
    app:
        container_name: ace-app
        image: "quik/aceoperator-app:${project.version}"
        depends_on:
          - mail
          - data
        links:
          - "data:data"
          - "mail:mail"
        networks:
          - "network"
        environment:
          - "ACE_DATA_HOST=${ACE_DATA_HOST}"
        volumes:
          - "${ACEOPERATOR_HOME}:/var/aceoperator"
    frontend:
        container_name: ace-frontend
        image: "quik/aceoperator-frontend:${project.version}"
        ports:
          - "80:80"
          - "443:443"
        links:
          - "app:app"
        networks:
          - "network"       
networks:
  network:
    driver: bridge
volumes:
  acedb: