version: "2"
services:
    app:
        container_name: ace-app
        image: "quik/aceoperator-app:${project.version}"
        depends_on:
          - mail
          - data
        links:
          - "data:data"
          - "mail:mail"
        networks:
          - "network"
        volumes:
          - "${ACEOPERATOR_HOME}:/var/aceoperator"
    frontend:
        container_name: ace-frontend
        image: "quik/aceoperator-frontend:${project.version}"
        ports:
          - "80:80"
          - "443:443"
        links:
          - "app:app"
        networks:
          - "network"       
networks:
  network:
    driver: bridge
volumes:
  acedb: