version: "2"
services:
    app:
        container_name: ace-app
        image: "quik/aceoperator-app:${project.version}"
        depends_on:
          - mail
          - db
        links:
          - "db:db"
          - "mail:mail"
        networks:
          - "network"
        environment:
          - "ACE_SQL_HOST=${ACE_SQL_HOST}"
          - "ACE_SQL_ROOT_PASSWORD=${ACE_SQL_ROOT_PASSWORD}"
          - "ACE_SQL_USER=${ACE_SQL_USER}"
          - "ACE_SQL_PASSWORD=${ACE_SQL_PASSWORD}"
          - "ACE_SMTP_SERVER=${ACE_SMTP_SERVER}"
          - "ACE_SMTP_USER=${ACE_SMTP_USER}"
          - "ACE_SMTP_PASSWORD=${ACE_SMTP_PASSWORD}"
          - "LOAD_DEMO=${LOAD_DEMO}"
          - "RUN_SEED=${RUN_SEED}"
         volumes:
          - ${ACEOPERATOR_HOME}:/var/aceoperator
    db:
        container_name: ace-db
        image: "quik/aceoperator-db:${project.version}"
        ports: 
          - "3306:3306"
        networks:
          - "network"
        environment:
          - "MYSQL_ROOT_PASSWORD=${ACE_SQL_ROOT_PASSWORD}"
    mail:
        container_name: ace-mail
        image: "quik/aceoperator-mail:${project.version}"
        ports:
          - "25:25"
          - "143:143" 
          - "993:993"
        networks:
          - "network"
    frontend:
        container_name: ace-frontend
        image: "quik/aceoperator-frontend:${project.version}"
        ports:
          - "80:80"
          - "443:443"
        links:
          - "app:app"
        networks:
          - "network"
          
networks:
  network:
    driver: bridge