version: "2"
services:
     data:
        container_name: ace-data
        image: "quik/aceoperator-data:${project.version}"
        links:
          - "db:${ACEOPERATOR_SQL_HOST}"
        networks:
          - "network"
        environment:
          - "ACEOPERATOR_SQL_HOST=${ACEOPERATOR_SQL_HOST}"
          - "ACEOPERATOR_SQL_PORT=${ACEOPERATOR_SQL_PORT}"
          - "ACEOPERATOR_SQL_DB=${ACEOPERATOR_SQL_DB}"
          - "ACEOPERATOR_SQL_ROOT_PASSWORD=${ACEOPERATOR_SQL_ROOT_PASSWORD}"
          - "ACEOPERATOR_SQL_USER=${ACEOPERATOR_SQL_USER}"
          - "ACEOPERATOR_SQL_PASSWORD=${ACEOPERATOR_SQL_PASSWORD}"
          - "ACEOPERATOR_ADMIN_PASSWORD=${ACEOPERATOR_ADMIN_PASSWORD}"

          - "ACE3_DATA_RUN_SEED=${ACE3_DATA_RUN_SEED}"
          - "ACE3_DATA_RUN_PATCH=${ACE3_DATA_RUN_PATCH}"

          - "ACE3_DATA_LOAD_USERS=${ACE3_DATA_LOAD_USERS}"
          - "ACE3_DATA_USERS=${ACE3_DATA_USERS}"
          - "ACE3_DATA_EMAIL_TRANSCRIPT=${ACE3_DATA_EMAIL_TRANSCRIPT}"

          - "ACE3_DATA_EXIT=false"
        volumes:
          - "${ACEOPERATOR_HOME}:/var/aceoperator"   
networks:
  network:
    driver: bridge
volumes:
  acedb: